# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Import from ParaTranz

on:
  repository_dispatch:
    types: [test_trigger]

  schedule:
    - cron:  '0 */3 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install translate-toolkit
        run: pip install translate-toolkit
      - name: Install regex
        run: pip install regex
      - name: Copy sources
        run: sudo sh ./Importer/copy_sources.sh
      - name: Run
        run: python ./Importer/main.py # CSV > HTMLの変換実行
        env:
          PARATRANZ_SECRET: ${{ secrets.PARATRANZ_SECRET }}
          PARATRANZ_CODE: ${{ secrets.PARATRANZ_CODE }}
      - name: Copy converted
        run: sudo sh ./Importer/copy_converted.sh
      - name: Zipper
        run: python ./Importer/zipper.py # マニュアルの内容をアーカイブ化
      - name: Push
        run: sudo sh ./Importer/push.sh # 変更があればコミット&プッシュ
      - name: Set COMMIT_DATE
        run: echo ::set-env name=COMMIT_DATE::$(TZ=UTC-9 date '+%Y-%m-%d %H:%M:%S' | tr '\n' ' ')
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ env.action_state != 'yellow' && env.DISCORD_WEBHOOK}}
        uses: Ilshidur/action-discord@master # Discordへの更新通知
        with:
          # https://git.io/で生成した短縮URLを入れると便利かもしれません
          # args: 'ParaTranzの翻訳をオンラインヘルプに反映: ${{ env.COMMIT_DATE }} - https://git.io/*****'
          args: 'ParaTranzの翻訳をオンラインヘルプに反映: ${{ env.COMMIT_DATE }}'
