# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Import from ParaTranz

on:
  repository_dispatch:
    types: [test_trigger]
    
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual Run'
        required: true
        default: 'Manual Import'

  schedule:
    - cron:  '0 */3 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install translate-toolkit
        run: pip install translate-toolkit
      - name: Install regex
        run: pip install regex
      - name: Install janome
        run: pip install janome
      - name: Install natsort
        run: pip install natsort
      - name: Copy sources
        run: sudo sh ./Importer/copy_sources.sh
      - name: Run
        run: python ./Importer/main.py # CSV > HTMLの変換実行
        env:
          PARATRANZ_SECRET: ${{ secrets.PARATRANZ_SECRET }}
          PARATRANZ_CODE: ${{ secrets.PARATRANZ_CODE }}
      - name: Copy converted
        run: sudo sh ./Importer/copy_converted.sh
      - name: Set Env
        run: |
             echo "$(<_ENV_ACTION_STATE)" >> $GITHUB_ENV
             echo "$(<_ENV_TAG)" >> $GITHUB_ENV
             echo "$(<_ENV_VER)" >> $GITHUB_ENV
             echo "$(<_ENV_GENERATE_EX)" >> $GITHUB_ENV
             echo "$(<_ENV_DISCORD_MESSAGE)" >> $GITHUB_ENV
             ls
             rm -f _ENV_*
      - name: Show Env
        run: |
             ls
             echo "action_state = ${{ env.action_state }}"
             echo "release_tag = ${{ env.release_tag }}"
             echo "release_ver = ${{ env.release_ver }}"
             echo "generate_ex = ${{ env.generate_ex }}"
             echo "discord_message = ${{ env.discord_message }}"
      - name: Delete
        if: ${{ env.action_state != 'yellow'}}
        uses: ame-yu/action-delete-latest-release@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        id: create_release
        if: ${{ env.action_state == 'green'}}
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.release_tag }}
          release_name: v${{ env.release_ver }}
          draft: false
          prerelease: false
      - name: Upload Manual
        id: upload-release-asset_manual
        if: ${{ env.action_state == 'green'}}
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Release/YoYoStudioRoboHelp.zip
          asset_name: YoYoStudioRoboHelp.zip
          asset_content_type: application/zip
      - name: Upload Manual Alt
        id: upload-release-asset_manual_alt
        if: ${{ env.generate_ex == 'green'}}
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Release/YoYoStudioRoboHelp_Alt.zip
          asset_name: YoYoStudioRoboHelp_Alt.zip
          asset_content_type: application/zip
      - name: Upload CSV
        id: upload-release-asset_ide
        if: ${{ env.action_state == 'green'}}
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Release/japanese.csv
          asset_name: japanese.csv
          asset_content_type: text/csv
      - name: Upload CSV Alt
        id: upload-release-asset_ide_alt
        if: ${{ env.generate_ex == 'green'}}
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Release/japanese_alt.csv
          asset_name: japanese_alt.csv
          asset_content_type: text/csv
      - name: Push
        if: ${{ env.action_state == 'green'}}
        run: sudo sh ./Importer/push.sh # 変更があればコミット&プッシュ
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ env.action_state == 'green' && env.DISCORD_WEBHOOK}}
        uses: Ilshidur/action-discord@master # Discordへの更新通知
        with:
          args: '${{ env.discord_message }}'
