# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Import from ParaTranz

on:
  repository_dispatch:
    types: [test_trigger]
    
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual Run'
        required: true
        default: 'Manual Import'

  schedule:
#    - cron:  '1 0 */1 * *' # 一日に一度
#    - cron:  '1 */3 * * *' # 3時間
    - cron:  '1 */3 * * *' # 1時間30分 (1)
    - cron:  '31 1-23/3 * * *' # 1時間30分 (2)
#    - cron:  '1 */1 * * *' # 1時間 (ParaTranzのアーカイブ生成時間に合わせた最小実行時間)

jobs:
  generate:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          lfs: true
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Install translate-toolkit
        run: pip install translate-toolkit
      - name: Install regex
        run: pip install regex
      - name: Install janome
        run: pip install janome
      - name: Install natsort
        run: pip install natsort
      - name: Copy sources
        run: sudo sh ./Importer/copy_sources.sh
      - name: Run
        run: python -B ./Importer/main.py # CSV > HTMLの変換を実行
        env:
          PARATRANZ_SECRET: ${{ secrets.PARATRANZ_SECRET }}
          PARATRANZ_CODE: ${{ secrets.PARATRANZ_CODE }}
          REPOSITORY_NAME: ${{ github.repository }}
      - name: Copy converted
        run: sudo bash ./Importer/copy_converted.sh
      - name: Set Env
        run: |
             echo "$(<_ENV_ACTION_STATE)" >> $GITHUB_ENV
             echo "$(<_ENV_TAG)" >> $GITHUB_ENV
             echo "$(<_ENV_VER)" >> $GITHUB_ENV
             echo "$(<_ENV_DISCORD_MESSAGE)" >> $GITHUB_ENV
             rm -f _ENV_*
      - name: Write Release Stats
        if: ${{ env.action_state == 'green'}}
        run: python ./Importer/write_release_stats.py
        env:
          REPOSITORY_NAME: ${{ github.repository }}
      - name: Set FILES
        if: ${{ env.action_state == 'green'}}
        id: file_path
        run: echo ::set-output name=path::$(for file in `ls Release/`;do echo Release/$file;done)
      - name: Github Release create, update, and upload assets
        if: ${{ env.action_state == 'green'}}
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.release_tag }}
          name: v${{ env.release_ver }}
          files: >
            ${{ steps.file_path.outputs.path }}
          draft: false
          gzip: false
          allow_override: true
      - name: Push
        if: ${{ env.action_state == 'green'}}
        run: sudo sh ./Importer/push.sh # 変更があればコミット&プッシュ
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ env.action_state == 'green' && env.DISCORD_WEBHOOK}}
        uses: Ilshidur/action-discord@master # Discordへの更新通知
        with:
          args: '${{ env.discord_message }}'
